---
- name: Stop Docker
  systemd:
    name: docker
    state: stopped
    enabled: false
  become: "{{ k3s_become_for_uninstall | ternary(true, false, k3s_become_for_all) }}"
- name: Uninstall Docker
  pacman:
    name: docker
    state: absent
  register: ensure_docker_uninstalled
  until: ensure_docker_uninstalled is succeeded
  retries: 3
  delay: 10
  become: "{{ k3s_become_for_uninstall | ternary(true, false, k3s_become_for_all) }}"